"""add bilingual fields to projects

Revision ID: 4540bf609dfc
Revises: 34a09f632df3
Create Date: 2026-01-25 23:29:45.315254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4540bf609dfc'
down_revision = '34a09f632df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_es', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('summary_es', sa.String(length=280), nullable=False))
        batch_op.add_column(sa.Column('description_es', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('video_url', sa.String(length=240), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('description_es')
        batch_op.drop_column('summary_es')
        batch_op.drop_column('title_es')

    # ### end Alembic commands ###
